# Copy Number Signature Identification {#cnsig}

## Introduction {-}

Unlike several mutation types presented in current COSMIC database for generating mutational signatures, it is hard to represent copy number features and generate the matrix for NMF decomposition.

@macintyre2018copy created a new method to generate the matrix for extracting signature by non-negative matrix factorization (NMF) algorithm. The steps are:

- derive 6 copy number features from absolute copy number profile
- apply mixture modelling to breakdown each feature distribution into mixtures of Gaussian or mixtures of Poisson distributions
- generate a sample-by-component matrix representing the sum of posterior probabilities of each copy-number event being assigned to each component.

Based on previous work, our group devised a new method which discards the statistical modeling and create a fixed number of predefined components from 8 copy number features to generate the matrix as the input of NMF,
it is easier to reproduce the result, apply to different cancer types and compare results.
To test if the method would works, we applied it to prostate cancer and successfully identified 5 copy number signatures.

Currently, there are few studies focus on copy number signatures and no reference signature database for matching and explaining the etiologies. If you study them, you should do extra work to explore and validate them. Furthermore, the input absolute copy number data may be generated by different methods and platforms, it is normal that the contribution of some copy number feature components varies a little and result in relatively lower signature similarity when comparing different cohorts or different copy number profile generation methods.

## Read Data {-}

## Tally Components {-}

## Extract Signatures {-}

