---
title: "Sigminer: Mutational Signature Extraction, Analysis and Visualization Pipeline"
author: ["Shixiang Wang", "Tao Wu", "Ziyu Tao", "Xue-Song Liu"]
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: vignette
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ABSTRACT

Mutational signature analysis has become a routine after somatic variant calling from high-throughput DNA sequencing.
Several tools for discovering *de novo* signatures from mutation catalogues of multiple samples or fitting reference signatures based on mutation catalogues of single sample have been published, but lack of interactivity and extensibility. Here we present an R/CRAN package to provide a one-stop solution for extracting, analyzing and visualizing mutational signatures.

**Availability and implementation**: sigminer is implemented as a CRAN package in R. The package can be downloaded either from <https://cran.r-project.org/> or <https://github.com/ShixiangWang/sigminer>. The package manual can be viewed at <https://shixiangwang.github.io/sigminer-doc/>.

**Contact**: <liuxs@shanghaitech.edu.cn>

## 1. INTRODUCTION

To be written by Prof. Liu


## 2. DESCRIPTION

### 2.1 *De novo* signatures discovery

### 2.2 Reference signatures fitting

## 3. DISCUSSION


## ACKNOWLEDGEMENT

*Funding*:

*Conflict of Interest*: none declared.

## REFERENCES