---
title: "Signature Analysis Workflows with sigminer"
subtitle: "A clear illustration"
author: ["Shixiang Wang", "Tao Wu", "Ziyu Tao", "Xue-Song Liu"]
institute: "ShanghaiTech University"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: vignette
    toc: true
---

```{r init, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  tidy = TRUE, 
  warning = FALSE, message = FALSE
)
```

> Contact:
>
> Xue-Song Liu: <liuxs@shanghaitech.edu.cn>
>
> Shixiang Wang: <wangshx@shanghaitech.edu.cn>

This vignette uses a TCGA breast mutation dataset to show how to analyze [mutational signatures](https://cancer.sanger.ac.uk/cosmic/signatures) with [{sigminer}](https://cran.r-project.org/web/packages/sigminer/index.html).


## Data Import

```{r}
library()
maf <- GDCquery_Maf("CHOL", pipelines = "muse")
```


## Workflow 1: *de novo* Signatures Discovery

## Workflow 2: Reference Signatures Fitting

## Session

```{r}
devtools::session_info()
```

